#
# This file contains additional services for FAForever that are highly relevant but uncritical to run FAF.
#
version: '3.7'

services:

  #
  # Static copy of the old phpbb3 forum (https://forums.faforever.com)
  #
  phpbb3-archive:
    image: nginx:1.19
    restart: unless-stopped
    volumes:
      - ./config/extra/phpbb3-archive/:/etc/nginx/conf.d/
      - ./data/phpbb3-archive/:/usr/share/nginx/html/
    networks:
      - faf-extra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faf-phpbb3-archive.rule=Host(`forums.${DOMAINNAME}`)"
      - "traefik.http.routers.faf-phpbb3-archive.entryPoints=web-secure"
      - "traefik.http.routers.faf-phpbb3-archive.middlewares=test-compress@file"

  #
  # NoSQL database specifically used for nodebb
  #
  mongodb:
    image: mongo:4.2.13
    user: ${FAF_MONGODB_USER}
    restart: unless-stopped
    networks:
      - faf-extra
    env_file: ./config/extra/mongodb/mongodb.env
    volumes:
      - ./data/faf-mongodb/data/db:/data/db

  #
  # Forum software
  #
  nodebb:
    # for instructions how to initialize the setup check the readme in the config.template/faf-nodebb
    image: nodebb/docker:v1.16.2
    user: ${FAF_NODEBB_USER}
    restart: unless-stopped
    networks:
      - faf-extra
      - faf # for interaction with the API (OAuth login and user synchronization)
    volumes:
      - ./config/extra/nodebb/config.json:/usr/src/app/config.json
      - ./data/nodebb/node_modules:/usr/src/app/node_modules
      - ./data/nodebb/build:/usr/src/app/build
      - ./data/nodebb/uploads/:/usr/src/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faf-nodebb.rule=Host(`forum.${DOMAINNAME}`)"
      - "traefik.http.routers.faf-nodebb.entryPoints=web-secure"
      - "traefik.http.routers.faf-nodebb.middlewares=test-compress@file"


  #
  # Wiki software (same as Wikipedia)
  #
  mediawiki:
    image: mediawiki:lts
    user: ${FAF_WIKI_USER}
    restart: unless-stopped
    networks:
      - faf-extra
    volumes:
      - ./data/mediawiki/images:/var/www/html/images
      - ./data/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
    env_file: ./config/extra/mediawiki/mediawiki.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faf-wiki.rule=Host(`wiki.${DOMAINNAME}`)"
      - "traefik.http.routers.faf-wiki.entryPoints=web-secure"


  #
  # FAF unit database
  #
  unitdb:
    image: faforever/faf-unitdb:v1.3.1
    restart: unless-stopped
    networks:
      - faf-extra
    volumes:
      - ./config/extra/unitdb/datafiles.json:/var/www/html/config/datafiles.json
      - ./config/extra/unitdb/locfiles.json:/var/www/html/config/locfiles.json
    env_file: ./config/extra/unitdb/unitdb.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faf-unitdb.rule=Host(`unitdb.${DOMAINNAME}`) || Host(`direct.${DOMAINNAME}`) && PathPrefix(`/faf/unitsDB`)"
      - "traefik.http.routers.faf-unitdb.entryPoints=web-secure"
      - "traefik.http.routers.faf-unitdb.middlewares=unitdb-stripprefix, test-compress@file"
      - "traefik.http.middlewares.unitdb-stripprefix.stripprefix.prefixes=/faf/unitsDB"


  #
  # Web frontend for voting
  #
  voting:
    image: faforever/faf-voting:v2.0.3
    user: ${FAF_VOTING_USER}
    restart: unless-stopped
    networks:
      - faf-extra
    env_file: ./config/extra/voting/voting.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faf-voting.rule=Host(`voting.${DOMAINNAME}`)"
      - "traefik.http.routers.faf-voting.entryPoints=web-secure"
      - "traefik.http.routers.faf-voting.middlewares=test-compress@file"
      - "traefik.http.services.faf-voting.loadbalancer.server.port=3000"


networks:
  faf-extra:
    driver: bridge
  faf:
    driver: bridge