#
# This file contains additional services for FAForever that are highly relevant but uncritical to run FAF.
#
version: '3.7'

services:

  #
  # NoSQL database specifically used for nodebb
  #
  mongodb:
    image: mongo:6.0.3-focal
    restart: unless-stopped
    networks:
      - faf-extra
    env_file: ./config/extra/mongodb/mongodb.env
    volumes:
      - ./data/mongodb/data/db:/data/db
      # Mongodump is corrupting the backup file when piping out via stdout
      - ./data/mongodb/backup:/backup

  #
  # Forum software
  #
  nodebb:
    # for instructions how to initialize the setup check the readme in the config.template/faf-nodebb
    image: nodebb/docker:1.18.5
    restart: unless-stopped
    networks:
      - faf-extra
      - faf # for interaction with the API (OAuth login and user synchronization)
    volumes:
      - ./config/extra/nodebb/config.json:/usr/src/app/config.json
      - ./data/nodebb/node_modules:/usr/src/app/node_modules
      - ./data/nodebb/build:/usr/src/app/build
      - ./data/nodebb/uploads/:/usr/src/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faf-nodebb.rule=Host(`forum.${DOMAINNAME}`)"
      - "traefik.http.routers.faf-nodebb.entryPoints=websecure"

networks:
  faf-extra:
    driver: bridge
  faf:
    driver: bridge
