#
# This file contains additional services for FAForever that are highly relevant but uncritical to run FAF.
#
version: '3.7'

services:

  #
  # NoSQL database specifically used for nodebb
  #
  mongodb:
    image: mongo:6.0.3-focal
    restart: unless-stopped
    networks:
      - faf-extra
    env_file: ./config/extra/mongodb/mongodb.env
    volumes:
      - ./data/mongodb/data/db:/data/db
      # Mongodump is corrupting the backup file when piping out via stdout
      - ./data/mongodb/backup:/backup

networks:
  faf-extra:
    driver: bridge
  faf:
    driver: bridge
