#
# This file contains additional services for FAForever that are highly relevant but uncritical to run FAF.
#
version: '3.7'

services:
  #
  # Static copy of the old phpbb3 forum (https://forums.faforever.com)
  #
  phpbb3-archive:
    image: nginx:1.25
    restart: unless-stopped
    volumes:
      - ./config/extra/phpbb3-archive/:/etc/nginx/conf.d/
      - ./data/phpbb3-archive/:/usr/share/nginx/html/
    networks:
      - faf-extra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faf-phpbb3-archive.rule=Host(`forums.${DOMAINNAME}`)"
      - "traefik.http.routers.faf-phpbb3-archive.entryPoints=websecure"

  #
  # FAF unit database
  #
  unitdb:
    image: faforever/faf-unitdb:v1.3.1
    restart: unless-stopped
    networks:
      - faf-extra
    volumes:
      - ./config/extra/unitdb/datafiles.json:/var/www/html/config/datafiles.json
      - ./config/extra/unitdb/locfiles.json:/var/www/html/config/locfiles.json
    env_file: ./config/extra/unitdb/unitdb.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faf-unitdb.rule=Host(`unitdb.${DOMAINNAME}`) || Host(`direct.${DOMAINNAME}`) && PathPrefix(`/faf/unitsDB`)"
      - "traefik.http.routers.faf-unitdb.entryPoints=websecure"
      - "traefik.http.routers.faf-unitdb.middlewares=unitdb-stripprefix"
      - "traefik.http.middlewares.unitdb-stripprefix.stripprefix.prefixes=/faf/unitsDB"


  #
  # Web frontend for voting
  #
  voting:
    image: faforever/faf-voting:v2.1.1
    user: ${FAF_VOTING_USER}
    restart: unless-stopped
    networks:
      - faf-extra
    env_file: ./config/extra/voting/voting.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faf-voting.rule=Host(`voting.${DOMAINNAME}`)"
      - "traefik.http.routers.faf-voting.entryPoints=websecure"
      - "traefik.http.services.faf-voting.loadbalancer.server.port=3000"


  #
  # New Wiki software (not the same as Wikipedia)
  #
  wikijs:
    image: requarks/wiki:2
    restart: unless-stopped
    networks:
      - faf-extra
    env_file: ./config/extra/wikijs/wikijs.env
    volumes:
      - ./data/wikijs/authentication/faf-hydra:/wiki/server/modules/authentication/faf-hydra:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wikijs.rule=Host(`wiki.${DOMAINNAME}`)"
      - "traefik.http.routers.wikijs.entryPoints=websecure"
      - "traefik.http.services.wikijs.loadbalancer.server.port=3000"

  #
  # Database used by Wiki.js
  #
  postgres-wikijs:
    image: postgres:13-alpine
    restart: unless-stopped
    networks:
      - faf-extra
    env_file: ./config/extra/postgres-wikijs/postgres-wikijs.env
    volumes:
      - ./data/extra/postgres-wikijs:/var/lib/postgresql/data

  #
  # QAI & Dostya combined
  #
  qai:
    image: faforever/faf-qai:main
    restart: unless-stopped
    networks:
      - faf
    env_file: ./config/extra/qai/qai.env
    volumes:
      - ./data/qai/Database:/app/Database

networks:
  faf-extra:
    driver: bridge
  faf:
    driver: bridge
