logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

# Enable Web Provider.
[api]
  dashboard = true

# Enable dynamic editing of additional rules
[file]
  filename = "/etc/traefik/rules.toml"
  watch = true

# Enable docker listening
[docker]
  endpoint = "unix:///var/run/docker.sock"
  network = "faf"
  domain = "faforever.localhost"
  watch = true
  exposedByDefault = false

# Force HTTPS
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

# Let's encrypt configuration
[acme]
  email="admin@localhost.com"
  storage="/etc/traefik/acme.json"
  entryPoint="https"
  acmeLogging=true
  onHostRule=true
  [acme.httpChallenge]
    entryPoint = "http"
