server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "info"
                  
positions:
    filename: /tmp/positions.yaml
                        
clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: docker_logs
      docker_sd_configs:
          - host: unix:///var/run/docker.sock
            refresh_interval: 5s
      pipeline_stages:
        - docker: {}
      relabel_configs:
          - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
            target_label: 'service'
          - source_labels: ['__meta_docker_container_label_loki_retention']
            target_label: 'loki_retention'
